In [2]:
import pandas as pd
import numpy as np
import ast
from collections import Counter

In [3]:
credits = pd.read_csv('tmdb_5000_credits.csv') #đọc dữ liệu
movies = pd.read_csv('tmdb_5000_movies.csv')

In [4]:
credits.head() #xem qua data

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
movies = movies.merge(credits, left_on='title', right_on='title') #merge 2 file data và 1 file movie

In [7]:
movies.head() #check lại data

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']] #chỉ giữ lại những cột này

In [9]:
movies.head(1) #check lại data

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L
#Hàm convert(obj): Chuyển một chuỗi biểu diễn danh sách các đối tượng (dict) có khóa 'name' thành một danh sách chỉ chứa các giá trị 'name'.

In [11]:
movies['genres'] = movies['genres'].apply(convert)

In [12]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4809, dtype: object

In [13]:
movies['keywords'] = movies['keywords'].apply(convert)

In [14]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4809, dtype: object

In [15]:
movies['cast'] = movies['cast'].apply(lambda x: [i['name'] for i in ast.literal_eval(x)[:3]])  
# Chuyển chuỗi JSON đó thành danh sách thật của các dict Python
# Only top 3 actors
# Tạo danh sách chỉ chứa tên diễn viên

In [16]:
movies['crew'] = movies['crew'].apply(lambda x: [i['name'] for i in ast.literal_eval(x) if i['job'] == 'Director'])

In [17]:
movies['tags'] = movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

# tag của movie là gồm các cột genres, keywwords, cast, crew

In [18]:
movies['tags']

0       [Action, Adventure, Fantasy, Science Fiction, ...
1       [Adventure, Fantasy, Action, ocean, drug abuse...
2       [Action, Adventure, Crime, spy, based on novel...
3       [Action, Crime, Drama, Thriller, dc comics, cr...
4       [Action, Adventure, Science Fiction, based on ...
                              ...
4804    [Action, Crime, Thriller, united states–mexico...
4805    [Comedy, Romance, Edward Burns, Kerry Bishé, M...
4806    [Comedy, Drama, Romance, TV Movie, date, love ...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Dani...
4808    [Documentary, obsession, camcorder, crush, dre...
Name: tags, Length: 4809, dtype: object

In [19]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x)) #join lại bằng dấu cách

In [20]:
movies = movies[['movie_id', 'title', 'overview', 'tags']] #giờ dataframe movies có cột movies tag sẽ là tổng hợp của genres, keywords, cast, crew luôn

In [21]:
movies['tags'] = movies['tags'].apply(lambda x: x.lower())

In [22]:
movies = movies.reset_index(drop=True)

In [23]:
movies.head()

,movie_id,title,overview,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",action adventure fantasy science fiction cultu...
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",adventure fantasy action ocean drug abuse exot...
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,action adventure crime spy based on novel secr...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,action crime drama thriller dc comics crime fi...
4,49529,John Carter,"John Carter is a war-weary, former military ca...",action adventure science fiction based on nove...

In [24]:
class MyTfidfVectorizer:
    def __init__(self):
        self.vocab_ = {} # một dict tạo ánh xạ: từ -> index
        self.idf_ = None # vector idf dc tính sau

    def _tokenize(self, doc: str):
        # tags của bạn dạng "Action Adventure Tom_Hanks ..." nên split theo space là đủ
        return doc.lower().split()
    # chuyển thành chữ thường và tách theo khoảng trắng, mỗi từ dc tách ra gọi là 1 token, output sẽ là 1 list các từ đơn được tách ra

    def fit_transform(self, docs):
        """
        docs: iterable (list/Series) các chuỗi.
        Trả về: ma trận TF-IDF dạng numpy.ndarray shape (n_docs, n_terms)
        """
        # 1. Tokenize từng doc
        tokenized_docs = [self._tokenize(d) for d in docs]

# tokenized_docs sẽ là ma trận 2 chiều như này
#[
#    ["action", "adventure", "tom_hanks"],      # mỗi dòng này là tag của từng phim, mà tag của từng phim lại dc split thành list các token
#    ["comedy", "romance", "jennifer_lawrence"], 
#    ["sci-fi", "action", "tom_cruise"]        
#]
        # 2. Xây vocab
        vocab = {}
        for tokens in tokenized_docs: # duyệt qua tag của từng phim 1, từng row
            for t in tokens: #trong tag của 1 phim thì lại là list các token của tag đó nên duyệt qua từng từ
                if t not in vocab: # nếu từ đấy chưa dc đánh index
                    vocab[t] = len(vocab) # thì key = từ đó, value bằng len của vocab lúc đó
        self.vocab_ = vocab

        n_docs = len(tokenized_docs) # số lượng documents (phim) trong dataset
        n_terms = len(vocab) # số lượng từ khác nhau

        # 3. Tính TF (term frequency) & DF (document frequency)
        X = np.zeros((n_docs, n_terms), dtype=np.float32) #khởi tạo ma trận tf ban đầu (x), hàng là các phim, cột là các từ khác nhau
        df_counts = np.zeros(n_terms, dtype=np.int32) #tạo mảng df bản đầu (1d) 
        for i, tokens in enumerate(tokenized_docs): # i là stt phim thứ i, tokens là list các từ đã tách của phim i
            counts = Counter(tokens) # đếm tần suất từ trong phim, trả về 1 dict key là từ, value là tần suất 
            #{'action': 1, 'adventure': 1, 'tom_hanks': 1}
            for t, c in counts.items(): #t là key, c là value
                j = vocab[t] #lấy index của từ trong vocab
                X[i, j] = c  #gán tf 
                df_counts[j] += 1 #tăng df
#tf là từ xuất hiện bao nhiêu lần trong 1 phim (một từ xhien nhiều trong 1 phim thì qtrong với phim đó)
#df là từ xuất hiện trong bao nhiêu phim (nhưng nếu từ đó xhien trong nhiều phim thì sẽ trở nên ít quan trọng)
        # 4. Tính IDF: giống công thức phổ biến của sklearn
        # idf_j = log((1 + n_docs) / (1 + df_j)) + 1
        idf = np.log((1.0 + n_docs) / (1.0 + df_counts)) + 1.0
        self.idf_ = idf

        # 5. TF-IDF = TF * IDF
        X *= idf

        # (Có thể chuẩn hóa theo độ dài doc nếu muốn giống sklearn hơn,
        # nhưng ở đây để đơn giản, chuẩn hóa sẽ làm ở bước cosine)
        return X

In [25]:
def cosine_similarity_custom(X: np.ndarray) -> np.ndarray:
    """
    X: ma trận (n_samples, n_features)
    Trả về: ma trận similarity (n_samples, n_samples)
    """
    # Chuẩn hóa từng vector hàng về norm = 1
    norms = np.linalg.norm(X, axis=1, keepdims=True) # tính norm theo từng hàng, giữ nguyên số chiều
    # Tránh chia cho 0
    norms = np.where(norms == 0, 1e-9, norms)
    #nếu norms = 0 thì thay bằng 0.00000..1, còn không thì giữ nguyên
    X_norm = X / norms # tính X_norm

    # Cosine similarity = X_norm * X_norm.T
    return X_norm @ X_norm.T #tính tích vô hướng

In [ ]:
tfidf = MyTfidfVectorizer() #tạo object từ class
vectors = tfidf.fit_transform(movies["tags"].values) 
    #gọi method fit_transform trên object tfidf, truyền data vào là cột tag
    # .values để đảm bảo là list/array các chuỗi
    #vectors là ma trận tf idf 
similarity = cosine_similarity_custom(vectors) 
    # tính similarity trên ma trận tf idf, output là ma trận n phim x n phim, 
    # mỗi ô [i,j] là độ tương đồng giữa phim i và j

In [28]:
def get_recommendations(title, cosine_sim=similarity):
    idx = movies[movies['title'] == title].index[0] # lấy index của phim có title = title cần tìm
    sim_scores = list(enumerate(cosine_sim[idx])) # cosine_sim[index] để lấy độ tương đồng của phim idx với các phim khác. VD cosine_sim[0] = [1.0, 0.43, 0.12, 0.09, ...]
    #enumurate gắn chỉ số phim tương ứng với giá trị similarity. VD [(0, 1.0), (1, 0.43), (2, 0.12), (3, 0.09), ...]
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True) #sort theo độ similarity
    sim_scores = sim_scores[1:11]  # Get top 10 similar movies
    movie_indices = [i[0] for i in sim_scores] # lấy ds chỉ số của 10 phim đó
    return movies['title'].iloc[movie_indices] # trả về title 10 phim

In [29]:
print(get_recommendations('The Dark Knight Rises'))

65               The Dark Knight
119                Batman Begins
1360                      Batman
210               Batman & Robin
428               Batman Returns
1361                      Batman
1197                The Prestige
303                     Catwoman
4644    Amidst the Devil's Wings
72                 Suicide Squad
Name: title, dtype: object